#remote_theme: mmistakes/minimal-mistakes
description:    Welcome, this is Jiaixn's homepage, have fun :)
layout: post
title: "Jiaxin's Site"
theme: jekyll-theme-dinky

#menu:
#  - title: 'Home'
#    url: '/'
#  - title: 'Fork'
#    url: 'http://github.com/aron-bordin/neo-hpstr-jekyll-theme'

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme
  - jekyll-include-cache
  
author:
  name   : "Jiaxin Lin"
  avatar : "src/IMG_8071.PNG"
  email  : "jx_linlin@126.com"
