remote_theme: aron-bordin/neo-hpstr-jekyll-theme
description:    Welcome, this is Jiaixn's homepage, have fun :)
layout: post
title: "Jiaxin's Site"
#theme: jekyll-theme-dinky

#menu:
#  - title: 'Home'
#    url: '/'
#  - title: 'Fork'
#    url: 'http://github.com/aron-bordin/neo-hpstr-jekyll-theme'
    
owner:
  name:           Jiaxin Lin
  email:          jx_linlin@126.com
  
plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-include-cache
